### PR TITLE
Added Closing method

### PR DESCRIPTION
**Pull request by ewoutp**
Method signals that the server is about to shutdown.

### CODE REVIEW

**Comment by ewoutp** [comment]
@zyndiecate RFR

**Comment by zyndiecate** [comment]
What is the idea behind that? Why not having a callback that is called when the server is shutting down? Maybe having this in addition? Lets talk about the bigger picture.

**Comment by ewoutp** [comment]
I wanted to keep it simple and just have a flag that signals the "shutting down" status.

**Comment by ZeissS** [comment]
LGTM, although I am still for removing all of the signal logic from the middleware-server.

**Pull request merged**
